spring.application.name=demo
spring.datasource.url=jdbc:mysql://mysql-37218507-proiect.h.aivencloud.com:16871/Proiect1

spring.datasource.username=avnadmin
spring.datasource.password=AVNS_G86nntv5hQTv7VIITFG
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
